### ISSUE TITLE
Crash when doing "get info" and library is empty

### ISSUE THREAD

**Issue by colin-marshall** [jcm93/jmc#26]
To reproduce:

- Have no songs in library
- right click library and choose Get info

Additionally, if there are songs in the library but you have none selected, you can right click and do get info and this loads the get info window for the song that is currently playing. If there is no song loaded then you get the crash again. To fix this for all situations I would suggest disabling the option to "get info" if there is no track selected when you right click.

**Comment by jcm93** [comment]
Fixed in [0.2 beta 5](https://github.com/jcm93/jmc/releases/tag/v0.2-beta.5).
