### ISSUE TITLE
Project Abandoned?

### ISSUE THREAD

**Issue by Porco-Rosso** [jcm93/jmc#44]
Hi, I'm just inquiring on if this project is still alive? 
Especially with Catalina ditching iTunes for _Music_ I am looking for an alternative. Was cheering this project along for some time, but it seems to have stalled.

**Comment by giorgiobrit** [comment]
Any news for update version ?

**Comment by gagarine** [comment]
It seem alive as there is new commit.

**Comment by jcm93** [comment]
Not completely dead.

I have been getting increasingly tired of Music.app so I made a few updates. No promises.
