### ISSUE TITLE
Keyboard audio controls [Feature Request]

### ISSUE THREAD

**Issue by colin-marshall** [jcm93/jmc#9]
Make jmc work with the stop, play, pause, etc. buttons on Apple keyboards.

**Comment by jcm93** [comment]
This is on my shortlist; I was trying to figure out if it was possible to implement this feature without having to register jmc as one of those "apps that can control your computer," which as far as I could tell would be necessary if I wanted to intercept these key events when the program was in the background as well as the foreground. I'll look into it a bit more.

**Comment by jcm93** [comment]
Implemented in commits 355a3c8 through 8135563.
